services:
  wordpress:
    image:  wordpress
    restart:  always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_USER: admin
      WORDPRESS_DB_PASSWORD: xxxxxxxx
      WORDPRESS_DB_NAME: wordpress1_db
      WORDPRESS_DB_HOST: projeto-wordpress.ctq4mmmgmide.us-east-1.rds.amazonaws.com
    volumes:
     - /efs/site:/var/www/html
